#!/bin/bash

datasets=(
#  NMME/COLA-RSMAS/CCSM4 
#  NMME/COLA-RSMAS/CESM1
  # NMME/ECCC/CanSIPS-IC4/hindcast 
  NMME/ECCC/CanSIPS-IC4/forecast
  # NMME/NASA-GMAO/GEOSS2S/hindcast 
  # NMME/NASA-GMAO/GEOSS2S/forecast
  # NMME/NOAA-GFDL/SPEAR/hindcast
  NMME/NOAA-GFDL/SPEAR/forecast
)

vars=(prcp t2m sst)


for ds in ${datasets[@]}; do
  for v in ${vars[@]}; do
    echo $ds/$v
    python -m sigrid.preprocess --parallel=0 $ds/$v
  done
done
